import type { ParsedDeal } from "./hubspot";

export const MOCK_DEALS: ParsedDeal[] = [
  {
    id: "mock-001",
    name: "Acme Corp",
    sub: "Enterprise Digital Suite",
    val: 420000,
    valShort: "$420.0K",
    rep: "george",
    stage: "Decision Maker Bought In",
    stageClass: "stage-neg",
    cat: "neg",
    closeDate: "2026-03-28",
    stageAge: 4,
    persona: "Enterprise Brand",
    revenueLine: "Canada",
    meddic: {
      metrics: "green",
      econBuyer: "green",
      decisionCriteria: "green",
      decisionProcess: "amber",
      identifyPain: "green",
      champion: "green",
    },
    contacts: [
      { name: "Sarah Chen", role: "VP Marketing", initials: "SC" },
      { name: "Tom Briggs", role: "CFO", initials: "TB" },
    ],
    nda: "signed",
    msa: "draft",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Strong Q1 budget cycle. Decision expected by end of March.",
    action1: "Draft MSA",
    action2: "Negotiate Terms",
    hsId: "mock-001",
    description: "",
    domain: null,
  },
  {
    id: "mock-002",
    name: "Bright Media Group",
    sub: "Programmatic Display",
    val: 185000,
    valShort: "$185.0K",
    rep: "george",
    stage: "Presentation Scheduled",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-04-15",
    stageAge: 8,
    persona: "Partner Media",
    revenueLine: "Canada",
    meddic: {
      metrics: "amber",
      econBuyer: "green",
      decisionCriteria: "amber",
      decisionProcess: "",
      identifyPain: "green",
      champion: "amber",
    },
    contacts: [
      { name: "Lisa Park", role: "Director of Media", initials: "LP" },
    ],
    nda: "signed",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Follow Up Proposal",
    action2: "Confirm Decision Maker",
    hsId: "mock-002",
    description: "",
    domain: null,
  },
  {
    id: "mock-003",
    name: "Sterling & Partners",
    sub: "Full-Stack Agency Package",
    val: 310000,
    valShort: "$310.0K",
    rep: "andy",
    stage: "Decision Maker Bought In",
    stageClass: "stage-neg",
    cat: "neg",
    closeDate: "2026-03-22",
    stageAge: 3,
    persona: "Partner Agency",
    revenueLine: "UK",
    meddic: {
      metrics: "green",
      econBuyer: "green",
      decisionCriteria: "green",
      decisionProcess: "green",
      identifyPain: "green",
      champion: "amber",
    },
    contacts: [
      { name: "James Whitfield", role: "Managing Partner", initials: "JW" },
      { name: "Emma Rodriguez", role: "Head of Digital", initials: "ER" },
    ],
    nda: "signed",
    msa: "signed",
    sow: "draft",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "UK agency expanding into programmatic. Strong fit with our platform.",
    action1: "Prepare SOW",
    action2: "Get Signature",
    hsId: "mock-003",
    description: "",
    domain: null,
  },
  {
    id: "mock-004",
    name: "NovaTech Solutions",
    sub: "SEM + Social Package",
    val: 95000,
    valShort: "$95.0K",
    rep: "andy",
    stage: "Presentation Scheduled",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-04-30",
    stageAge: 12,
    persona: "Enterprise Brand",
    revenueLine: "UK",
    meddic: {
      metrics: "amber",
      econBuyer: "",
      decisionCriteria: "amber",
      decisionProcess: "",
      identifyPain: "green",
      champion: "",
    },
    contacts: [
      { name: "Oliver Hughes", role: "CMO", initials: "OH" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Send NDA",
    action2: "Prepare Proposal",
    hsId: "mock-004",
    description: "",
    domain: null,
  },
  {
    id: "mock-005",
    name: "Pinnacle Brands",
    sub: "Connected TV Launch",
    val: 275000,
    valShort: "$275.0K",
    rep: "george",
    stage: "Qualified to Buy",
    stageClass: "stage-lead",
    cat: "leads",
    closeDate: "2026-05-15",
    stageAge: 2,
    persona: "Enterprise Brand",
    revenueLine: "Canada",
    meddic: {
      metrics: "",
      econBuyer: "",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "green",
      champion: "",
    },
    contacts: [
      { name: "Mark Davidson", role: "VP Growth", initials: "MD" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Qualify Budget",
    action2: "Book Presentation",
    hsId: "mock-005",
    description: "",
    domain: null,
  },
  {
    id: "mock-006",
    name: "Crestview Agency",
    sub: "White Label Platform",
    val: 150000,
    valShort: "$150.0K",
    rep: "alex",
    stage: "Appointment Scheduled",
    stageClass: "stage-lead",
    cat: "leads",
    closeDate: "2026-05-30",
    stageAge: 1,
    persona: "Partner Agency",
    revenueLine: "UK",
    meddic: {
      metrics: "",
      econBuyer: "",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "",
      champion: "",
    },
    contacts: [
      { name: "Rachel Kim", role: "Founder", initials: "RK" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Identify Pain Points",
    action2: "Schedule Discovery",
    hsId: "mock-006",
    description: "",
    domain: null,
  },
  {
    id: "mock-007",
    name: "Velocity Digital",
    sub: "Omnichannel Campaign",
    val: 520000,
    valShort: "$520.0K",
    rep: "andy",
    stage: "Qualified to Buy",
    stageClass: "stage-lead",
    cat: "leads",
    closeDate: "2026-06-01",
    stageAge: 5,
    persona: "Partner Media",
    revenueLine: "UK",
    meddic: {
      metrics: "amber",
      econBuyer: "",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "green",
      champion: "amber",
    },
    contacts: [
      { name: "David Clarke", role: "CEO", initials: "DC" },
      { name: "Nina Patel", role: "COO", initials: "NP" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Large media group looking to consolidate ad tech vendors.",
    action1: "Qualify Budget",
    action2: "Book Presentation",
    hsId: "mock-007",
    description: "",
    domain: null,
  },
  {
    id: "mock-008",
    name: "Horizon Retail Co",
    sub: "Geo-Targeted Display",
    val: 88000,
    valShort: "$88.0K",
    rep: "george",
    stage: "Decision Maker Bought In",
    stageClass: "stage-neg",
    cat: "neg",
    closeDate: "2026-03-18",
    stageAge: 10,
    persona: "Enterprise Brand",
    revenueLine: "Canada",
    meddic: {
      metrics: "green",
      econBuyer: "green",
      decisionCriteria: "green",
      decisionProcess: "green",
      identifyPain: "green",
      champion: "green",
    },
    contacts: [
      { name: "Karen Zhao", role: "Head of E-Commerce", initials: "KZ" },
    ],
    nda: "signed",
    msa: "signed",
    sow: "signed",
    credit: "approved",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Final legal review underway. Expecting signature this week.",
    action1: "Final Review",
    action2: "Close Deal",
    hsId: "mock-008",
    description: "",
    domain: null,
  },
  {
    id: "mock-009",
    name: "Atlas Media Network",
    sub: "Programmatic Video",
    val: 340000,
    valShort: "$340.0K",
    rep: "vendasta",
    stage: "Presentation Scheduled",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-04-20",
    stageAge: 7,
    persona: "Vendasta",
    revenueLine: "Vendasta",
    meddic: {
      metrics: "green",
      econBuyer: "amber",
      decisionCriteria: "green",
      decisionProcess: "amber",
      identifyPain: "green",
      champion: "green",
    },
    contacts: [
      { name: "Mike Sullivan", role: "Director of Partnerships", initials: "MS" },
    ],
    nda: "signed",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Follow Up Proposal",
    action2: "Confirm Decision Maker",
    hsId: "mock-009",
    description: "",
    domain: null,
  },
  {
    id: "mock-010",
    name: "Clearwater Financial",
    sub: "Digital Transformation",
    val: 190000,
    valShort: "$190.0K",
    rep: "alex",
    stage: "Presentation Scheduled",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-04-10",
    stageAge: 6,
    persona: "Partner Agency",
    revenueLine: "UK",
    meddic: {
      metrics: "green",
      econBuyer: "amber",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "green",
      champion: "amber",
    },
    contacts: [
      { name: "Sophie Winters", role: "Head of Strategy", initials: "SW" },
      { name: "Chris Hartley", role: "CTO", initials: "CH" },
    ],
    nda: "signed",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Fintech agency exploring white-label ad solutions.",
    action1: "Follow Up Proposal",
    action2: "Confirm Decision Maker",
    hsId: "mock-010",
    description: "",
    domain: null,
  },
];
