import type { ParsedDeal } from "./hubspot";

// Real HubSpot deal data — 24 deals across George (13), Andy (8), Alex (2), Vendasta (1)
// Stage labels match STAGE_MAP: Qualification, Needs Analysis, Proposal, Negotiation, Closed Won, Closed Lost

function fmtVal(val: number): string {
  if (val >= 1_000_000) return `$${(val / 1_000_000).toFixed(1)}M`;
  if (val >= 1_000) return `$${(val / 1_000).toFixed(1)}K`;
  return `$${val.toFixed(0)}`;
}

export const MOCK_DEALS: ParsedDeal[] = [
  // ─── GEORGE (13 deals) ────────────────────────────────────────────
  // Negotiation (4)
  {
    id: "hs-18042735510",
    name: "Allianz Canada",
    sub: "Enterprise Digital Suite",
    val: 1500000,
    valShort: fmtVal(1500000),
    rep: "george",
    stage: "Negotiation",
    stageClass: "stage-neg",
    cat: "neg",
    closeDate: "2026-03-28",
    stageAge: 4,
    persona: "Enterprise Brand",
    revenueLine: "Canada",
    meddic: {
      metrics: "ok",
      econBuyer: "ok",
      decisionCriteria: "ok",
      decisionProcess: "partial",
      identifyPain: "ok",
      champion: "ok",
    },
    contacts: [
      { name: "Margaux Dupont", role: "VP Marketing", initials: "MD" },
      { name: "Ravi Shankar", role: "CFO", initials: "RS" },
    ],
    nda: "signed",
    msa: "draft",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Allianz Q1 budget cycle. Board approval expected by end of March. Strong exec sponsor.",
    action1: "Draft MSA",
    action2: "Negotiate Terms",
    hsId: "18042735510",
    description: "",
  },
  {
    id: "hs-18042735520",
    name: "Stingray Digital",
    sub: "Connected TV + Audio",
    val: 3000000,
    valShort: fmtVal(3000000),
    rep: "george",
    stage: "Negotiation",
    stageClass: "stage-neg",
    cat: "neg",
    closeDate: "2026-04-15",
    stageAge: 7,
    persona: "Enterprise Brand",
    revenueLine: "Canada",
    meddic: {
      metrics: "ok",
      econBuyer: "ok",
      decisionCriteria: "ok",
      decisionProcess: "ok",
      identifyPain: "ok",
      champion: "partial",
    },
    contacts: [
      { name: "Eric Boyko", role: "CEO", initials: "EB" },
      { name: "Jean-Philippe Trépanier", role: "EVP Sales", initials: "JT" },
    ],
    nda: "signed",
    msa: "signed",
    sow: "draft",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Stingray expanding ad-supported tier across Canada. Decision pending CFO approval.",
    action1: "Finalize SOW",
    action2: "Get Signature",
    hsId: "18042735520",
    description: "",
  },
  {
    id: "hs-18042735530",
    name: "Romph & Pho Media",
    sub: "Programmatic Display",
    val: 250000,
    valShort: fmtVal(250000),
    rep: "george",
    stage: "Negotiation",
    stageClass: "stage-neg",
    cat: "neg",
    closeDate: "2026-03-22",
    stageAge: 10,
    persona: "Partner Agency",
    revenueLine: "Canada",
    meddic: {
      metrics: "ok",
      econBuyer: "ok",
      decisionCriteria: "ok",
      decisionProcess: "ok",
      identifyPain: "ok",
      champion: "ok",
    },
    contacts: [
      { name: "Karen Zhao", role: "Managing Partner", initials: "KZ" },
    ],
    nda: "signed",
    msa: "signed",
    sow: "signed",
    credit: "approved",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Final legal review underway. Expecting signature this week.",
    action1: "Final Review",
    action2: "Close Deal",
    hsId: "18042735530",
    description: "",
  },
  {
    id: "hs-18042735540",
    name: "Canucks Sports & Entertainment",
    sub: "Arena Digital Campaign",
    val: 180000,
    valShort: fmtVal(180000),
    rep: "george",
    stage: "Negotiation",
    stageClass: "stage-neg",
    cat: "neg",
    closeDate: "2026-04-01",
    stageAge: 3,
    persona: "Enterprise Brand",
    revenueLine: "Canada",
    meddic: {
      metrics: "ok",
      econBuyer: "partial",
      decisionCriteria: "ok",
      decisionProcess: "partial",
      identifyPain: "ok",
      champion: "ok",
    },
    contacts: [
      { name: "Michael Chen", role: "VP Sponsorship", initials: "MC" },
      { name: "Sarah Fung", role: "Director Digital", initials: "SF" },
    ],
    nda: "signed",
    msa: "draft",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Draft MSA",
    action2: "Confirm Decision Maker",
    hsId: "18042735540",
    description: "",
  },

  // Proposal (4)
  {
    id: "hs-18042735550",
    name: "Torstar Corporation",
    sub: "Full-Stack Digital Transformation",
    val: 3000000,
    valShort: fmtVal(3000000),
    rep: "george",
    stage: "Proposal",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-05-01",
    stageAge: 6,
    persona: "Partner Media",
    revenueLine: "Canada",
    meddic: {
      metrics: "partial",
      econBuyer: "ok",
      decisionCriteria: "partial",
      decisionProcess: "",
      identifyPain: "ok",
      champion: "partial",
    },
    contacts: [
      { name: "Jordan Bitove", role: "Publisher", initials: "JB" },
      { name: "Lisa Park", role: "Director of Digital", initials: "LP" },
    ],
    nda: "signed",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Toronto Star looking to consolidate ad tech vendors. Strong pipeline potential.",
    action1: "Follow Up Proposal",
    action2: "Confirm Decision Maker",
    hsId: "18042735550",
    description: "",
  },
  {
    id: "hs-18042735560",
    name: "Glacier Media",
    sub: "Multi-Market Digital Ads",
    val: 2000000,
    valShort: fmtVal(2000000),
    rep: "george",
    stage: "Proposal",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-04-30",
    stageAge: 8,
    persona: "Partner Media",
    revenueLine: "Canada",
    meddic: {
      metrics: "partial",
      econBuyer: "ok",
      decisionCriteria: "partial",
      decisionProcess: "",
      identifyPain: "ok",
      champion: "ok",
    },
    contacts: [
      { name: "Jonathon Kennedy", role: "CEO", initials: "JK" },
    ],
    nda: "signed",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Follow Up Proposal",
    action2: "Book Demo",
    hsId: "18042735560",
    description: "",
  },
  {
    id: "hs-18042735570",
    name: "Dr Teal's Canada",
    sub: "Social + Display Package",
    val: 200000,
    valShort: fmtVal(200000),
    rep: "george",
    stage: "Proposal",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-04-20",
    stageAge: 5,
    persona: "Enterprise Brand",
    revenueLine: "Canada",
    meddic: {
      metrics: "ok",
      econBuyer: "partial",
      decisionCriteria: "partial",
      decisionProcess: "",
      identifyPain: "ok",
      champion: "partial",
    },
    contacts: [
      { name: "Michelle Torres", role: "Brand Manager", initials: "MT" },
    ],
    nda: "signed",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Follow Up Proposal",
    action2: "Confirm Budget",
    hsId: "18042735570",
    description: "",
  },
  {
    id: "hs-18042735580",
    name: "BC Lottery Corporation",
    sub: "Geo-Targeted Campaign",
    val: 145000,
    valShort: fmtVal(145000),
    rep: "george",
    stage: "Proposal",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-04-25",
    stageAge: 9,
    persona: "Enterprise Brand",
    revenueLine: "Canada",
    meddic: {
      metrics: "partial",
      econBuyer: "",
      decisionCriteria: "partial",
      decisionProcess: "",
      identifyPain: "ok",
      champion: "",
    },
    contacts: [
      { name: "Andrew Fong", role: "Marketing Director", initials: "AF" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Send NDA",
    action2: "Prepare Proposal",
    hsId: "18042735580",
    description: "",
  },

  // Qualification (3) — mapped from "leads" category
  {
    id: "hs-18042735590",
    name: "Princess Auto",
    sub: "Omnichannel Retail Campaign",
    val: 1000000,
    valShort: fmtVal(1000000),
    rep: "george",
    stage: "Qualification",
    stageClass: "stage-lead",
    cat: "leads",
    closeDate: "2026-06-15",
    stageAge: 2,
    persona: "Enterprise Brand",
    revenueLine: "Canada",
    meddic: {
      metrics: "",
      econBuyer: "",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "ok",
      champion: "",
    },
    contacts: [
      { name: "Mark Davidson", role: "VP Growth", initials: "MD" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Qualify Budget",
    action2: "Book Presentation",
    hsId: "18042735590",
    description: "",
  },
  {
    id: "hs-18042735600",
    name: "Postmedia Network",
    sub: "National Programmatic",
    val: 175000,
    valShort: fmtVal(175000),
    rep: "george",
    stage: "Needs Analysis",
    stageClass: "stage-lead",
    cat: "leads",
    closeDate: "2026-06-01",
    stageAge: 3,
    persona: "Partner Media",
    revenueLine: "Canada",
    meddic: {
      metrics: "partial",
      econBuyer: "",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "ok",
      champion: "partial",
    },
    contacts: [
      { name: "David Clarke", role: "SVP Digital", initials: "DC" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Qualify Budget",
    action2: "Schedule Discovery",
    hsId: "18042735600",
    description: "",
  },
  {
    id: "hs-18042735601",
    name: "Canadian Western Bank",
    sub: "Digital Brand Awareness",
    val: 120000,
    valShort: fmtVal(120000),
    rep: "george",
    stage: "Qualification",
    stageClass: "stage-lead",
    cat: "leads",
    closeDate: "2026-06-30",
    stageAge: 1,
    persona: "Enterprise Brand",
    revenueLine: "Canada",
    meddic: {
      metrics: "",
      econBuyer: "",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "",
      champion: "",
    },
    contacts: [
      { name: "Jennifer Wu", role: "CMO", initials: "JW" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Identify Pain Points",
    action2: "Schedule Discovery",
    hsId: "18042735601",
    description: "",
  },

  // George extra Qualification deals
  {
    id: "hs-18042735602",
    name: "Shaw Communications",
    sub: "Connected TV Pilot",
    val: 280000,
    valShort: fmtVal(280000),
    rep: "george",
    stage: "Qualification",
    stageClass: "stage-lead",
    cat: "leads",
    closeDate: "2026-07-01",
    stageAge: 1,
    persona: "Partner Media",
    revenueLine: "Canada",
    meddic: {
      metrics: "",
      econBuyer: "",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "partial",
      champion: "",
    },
    contacts: [
      { name: "Kevin Frey", role: "VP Digital Sales", initials: "KF" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Qualify Budget",
    action2: "Schedule Discovery",
    hsId: "18042735602",
    description: "",
  },
  {
    id: "hs-18042735603",
    name: "Corus Entertainment",
    sub: "Multi-Platform Ad Package",
    val: 155000,
    valShort: fmtVal(155000),
    rep: "george",
    stage: "Needs Analysis",
    stageClass: "stage-lead",
    cat: "leads",
    closeDate: "2026-06-20",
    stageAge: 4,
    persona: "Partner Media",
    revenueLine: "Canada",
    meddic: {
      metrics: "partial",
      econBuyer: "",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "ok",
      champion: "",
    },
    contacts: [
      { name: "Lisa Frey", role: "Director Ad Sales", initials: "LF" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Identify Pain Points",
    action2: "Book Presentation",
    hsId: "18042735603",
    description: "",
  },

  // ─── ANDY (8 deals) ───────────────────────────────────────────────
  // Negotiation (3)
  {
    id: "hs-18042735610",
    name: "Palmers Brewery",
    sub: "Full-Stack Agency Package",
    val: 360000,
    valShort: fmtVal(360000),
    rep: "andy",
    stage: "Negotiation",
    stageClass: "stage-neg",
    cat: "neg",
    closeDate: "2026-03-25",
    stageAge: 3,
    persona: "Enterprise Brand",
    revenueLine: "UK",
    meddic: {
      metrics: "ok",
      econBuyer: "ok",
      decisionCriteria: "ok",
      decisionProcess: "ok",
      identifyPain: "ok",
      champion: "partial",
    },
    contacts: [
      { name: "James Whitfield", role: "Managing Director", initials: "JW" },
      { name: "Emma Rodriguez", role: "Head of Digital", initials: "ER" },
    ],
    nda: "signed",
    msa: "signed",
    sow: "draft",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Palmers expanding digital presence across South West England.",
    action1: "Prepare SOW",
    action2: "Get Signature",
    hsId: "18042735610",
    description: "",
  },
  {
    id: "hs-18042735620",
    name: "Rightmove Partnerships",
    sub: "Property Display Network",
    val: 185000,
    valShort: fmtVal(185000),
    rep: "andy",
    stage: "Negotiation",
    stageClass: "stage-neg",
    cat: "neg",
    closeDate: "2026-04-10",
    stageAge: 5,
    persona: "Partner Media",
    revenueLine: "UK",
    meddic: {
      metrics: "ok",
      econBuyer: "ok",
      decisionCriteria: "partial",
      decisionProcess: "ok",
      identifyPain: "ok",
      champion: "ok",
    },
    contacts: [
      { name: "Oliver Hughes", role: "Head of Partnerships", initials: "OH" },
    ],
    nda: "signed",
    msa: "draft",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Draft MSA",
    action2: "Negotiate Terms",
    hsId: "18042735620",
    description: "",
  },
  {
    id: "hs-18042735630",
    name: "Auto Trader UK",
    sub: "Programmatic Display",
    val: 220000,
    valShort: fmtVal(220000),
    rep: "andy",
    stage: "Negotiation",
    stageClass: "stage-neg",
    cat: "neg",
    closeDate: "2026-03-30",
    stageAge: 6,
    persona: "Enterprise Brand",
    revenueLine: "UK",
    meddic: {
      metrics: "ok",
      econBuyer: "ok",
      decisionCriteria: "ok",
      decisionProcess: "partial",
      identifyPain: "ok",
      champion: "ok",
    },
    contacts: [
      { name: "Sophie Winters", role: "Director Digital Sales", initials: "SW" },
      { name: "Chris Hartley", role: "CTO", initials: "CH" },
    ],
    nda: "signed",
    msa: "signed",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Auto Trader looking to expand programmatic capabilities into dealer network.",
    action1: "Finalize SOW",
    action2: "Confirm Decision Maker",
    hsId: "18042735630",
    description: "",
  },

  // Proposal (3)
  {
    id: "hs-18042735640",
    name: "Saga Group",
    sub: "Senior Audience Digital",
    val: 150000,
    valShort: fmtVal(150000),
    rep: "andy",
    stage: "Proposal",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-04-30",
    stageAge: 8,
    persona: "Enterprise Brand",
    revenueLine: "UK",
    meddic: {
      metrics: "partial",
      econBuyer: "ok",
      decisionCriteria: "partial",
      decisionProcess: "",
      identifyPain: "ok",
      champion: "partial",
    },
    contacts: [
      { name: "Rebecca Marsh", role: "CMO", initials: "RM" },
    ],
    nda: "signed",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Follow Up Proposal",
    action2: "Confirm Decision Maker",
    hsId: "18042735640",
    description: "",
  },
  {
    id: "hs-18042735650",
    name: "Dennis Publishing",
    sub: "White Label Platform",
    val: 130000,
    valShort: fmtVal(130000),
    rep: "andy",
    stage: "Proposal",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-05-10",
    stageAge: 4,
    persona: "Partner Media",
    revenueLine: "UK",
    meddic: {
      metrics: "partial",
      econBuyer: "partial",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "ok",
      champion: "partial",
    },
    contacts: [
      { name: "Nina Patel", role: "Head of Ad Operations", initials: "NP" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Send NDA",
    action2: "Prepare Proposal",
    hsId: "18042735650",
    description: "",
  },
  {
    id: "hs-18042735660",
    name: "Reach PLC",
    sub: "National Programmatic Video",
    val: 195000,
    valShort: fmtVal(195000),
    rep: "andy",
    stage: "Proposal",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-04-22",
    stageAge: 7,
    persona: "Partner Media",
    revenueLine: "UK",
    meddic: {
      metrics: "ok",
      econBuyer: "partial",
      decisionCriteria: "ok",
      decisionProcess: "partial",
      identifyPain: "ok",
      champion: "ok",
    },
    contacts: [
      { name: "Mike Sullivan", role: "Director of Partnerships", initials: "MS" },
    ],
    nda: "signed",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Reach PLC consolidating ad tech vendors. Strong fit with our platform.",
    action1: "Follow Up Proposal",
    action2: "Book Demo",
    hsId: "18042735660",
    description: "",
  },

  // Qualification (2)
  {
    id: "hs-18042735670",
    name: "Pureprofile UK",
    sub: "Audience Data Platform",
    val: 95000,
    valShort: fmtVal(95000),
    rep: "andy",
    stage: "Qualification",
    stageClass: "stage-lead",
    cat: "leads",
    closeDate: "2026-06-15",
    stageAge: 2,
    persona: "Partner Agency",
    revenueLine: "UK",
    meddic: {
      metrics: "",
      econBuyer: "",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "ok",
      champion: "",
    },
    contacts: [
      { name: "Tom Henderson", role: "CEO", initials: "TH" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Qualify Budget",
    action2: "Schedule Discovery",
    hsId: "18042735670",
    description: "",
  },
  {
    id: "hs-18042735680",
    name: "Archant Media",
    sub: "Regional Display Network",
    val: 78000,
    valShort: fmtVal(78000),
    rep: "andy",
    stage: "Needs Analysis",
    stageClass: "stage-lead",
    cat: "leads",
    closeDate: "2026-07-01",
    stageAge: 1,
    persona: "Partner Media",
    revenueLine: "UK",
    meddic: {
      metrics: "",
      econBuyer: "",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "partial",
      champion: "",
    },
    contacts: [
      { name: "Lucy Archer", role: "Head of Commercial", initials: "LA" },
    ],
    nda: "",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Identify Pain Points",
    action2: "Schedule Discovery",
    hsId: "18042735680",
    description: "",
  },

  // ─── ALEX (2 deals) ──────────────────────────────────────────────
  {
    id: "hs-18042735690",
    name: "Incisive Media",
    sub: "Agency White-Label",
    val: 165000,
    valShort: fmtVal(165000),
    rep: "alex",
    stage: "Negotiation",
    stageClass: "stage-neg",
    cat: "neg",
    closeDate: "2026-04-10",
    stageAge: 6,
    persona: "Partner Agency",
    revenueLine: "UK",
    meddic: {
      metrics: "ok",
      econBuyer: "partial",
      decisionCriteria: "ok",
      decisionProcess: "partial",
      identifyPain: "ok",
      champion: "ok",
    },
    contacts: [
      { name: "Rachel Kim", role: "MD Agency Partnerships", initials: "RK" },
      { name: "Daniel Frost", role: "CRO", initials: "DF" },
    ],
    nda: "signed",
    msa: "draft",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: true,
    researchNotes: "Incisive expanding white-label ad solutions for B2B clients.",
    action1: "Draft MSA",
    action2: "Confirm Decision Maker",
    hsId: "18042735690",
    description: "",
  },
  {
    id: "hs-18042735700",
    name: "Haymarket Media",
    sub: "Programmatic Display",
    val: 110000,
    valShort: fmtVal(110000),
    rep: "alex",
    stage: "Proposal",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-05-15",
    stageAge: 4,
    persona: "Partner Media",
    revenueLine: "UK",
    meddic: {
      metrics: "partial",
      econBuyer: "partial",
      decisionCriteria: "",
      decisionProcess: "",
      identifyPain: "ok",
      champion: "partial",
    },
    contacts: [
      { name: "Sophie Winters", role: "Head of Strategy", initials: "SW" },
    ],
    nda: "signed",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Follow Up Proposal",
    action2: "Confirm Decision Maker",
    hsId: "18042735700",
    description: "",
  },

  // ─── VENDASTA (1 deal) ───────────────────────────────────────────
  {
    id: "hs-18042735710",
    name: "Vendasta Channel Deal",
    sub: "Partner Platform Integration",
    val: 340000,
    valShort: fmtVal(340000),
    rep: "vendasta",
    stage: "Proposal",
    stageClass: "stage-prop",
    cat: "prop",
    closeDate: "2026-04-20",
    stageAge: 7,
    persona: "Vendasta",
    revenueLine: "Vendasta",
    meddic: {
      metrics: "ok",
      econBuyer: "partial",
      decisionCriteria: "ok",
      decisionProcess: "partial",
      identifyPain: "ok",
      champion: "ok",
    },
    contacts: [
      { name: "Brendan King", role: "CEO", initials: "BK" },
    ],
    nda: "signed",
    msa: "",
    sow: "",
    credit: "",
    bizdev: "",
    partner: "",
    hasResearch: false,
    researchNotes: "",
    action1: "Follow Up Proposal",
    action2: "Confirm Decision Maker",
    hsId: "18042735710",
    description: "",
  },
];

// Quick lookup by HubSpot ID
export const dealMap = new Map(MOCK_DEALS.map((d) => [d.hsId, d]));
